baseurl: ""
exclude: ["README.md"]
permalink: pretty
title: "Platformatory Labs"

google_analytics_id: "G-PWW2W71JX1"
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/plf-logo.svg"
  desktop: "images/logo/plf-logo.svg"
  desktop_height: "60px"
footer:
  copyright_text: "&copy; All rights reserved 2023. Platformatory LLC"

seo:
  meta_og_title: "Platformatory"
  meta_og_type: "website"
  meta_og_url: "http://platformatory.io"
  meta_og_image: "http://platformatory.io/images/logo/plf-logo.svg"
  meta_og_description: "Platform, Data & ML Engineering Studio"
  meta_twitter_card: "summary"
  meta_twitter_site: "@platformatory"
  meta_twitter_creator: "@platformatory"

collections:
  services:
    output: true
  team:
    output: true
  consulting:
    output: true
  solutions:
    output: true
  openings:
    output: true
  engineering:
    output: true
  field-engineering:
    output: true
  events:
    output: true
    permalink: /v2/events/:path
  education:
    output: true

# For events
future: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-menus
