baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Platformatory: Apache Kafka, Kong, Kubernetes, Modernization & Platform Strategy Consulting'

google_analytics_id: "G-PWW2W71JX1"
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/plf-logo.svg"
  desktop: "images/logo/plf-logo.svg"
  desktop_height: "60px"
footer:
  copyright_text: '&copy; All rights reserved 2023. Platformatory LLC'

seo:
  meta_og_title: "Platformatory"
  meta_og_type: "website"
  meta_og_url: "http://platformatory.io"
  meta_og_image: "http://platformatory.io/images/logo/platformatory2.svg"
  meta_og_description: "Cloud native engineering studio"
  meta_twitter_card: "summary"
  meta_twitter_site: "@platformatory"
  meta_twitter_creator: "@platformatory"

collections:
  services:
    output: true
  team:
    output: true
  consulting:
    output: true
  solutions:
    output: false
  openings:
    output: true
  engineering:
    output: true
  events:
    output: true
  publications:
    output: true

# For events        
future: true 

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-menus
